<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">
  <name>kit_robot</name>
  <version>0.0.0</version>
  <description>Kit robot controller with MoveIt2</description>

  <maintainer email="alekdi8gm30@gmail.com">min</maintainer>
  <license>TODO: License declaration</license>

  <!-- ROS2 -->
  <depend>rclpy</depend>
  <depend>ament_index_python</depend>
  <depend>kit_interfaces</depend>

  <!-- Controller -->
  <depend>builtin_interfaces</depend>

  <!-- MoveIt2 -->
  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>tf2_ros</depend>

  <!-- Python runtime -->
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-pymodbus</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>

  <!-- Test -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
